### ISSUE TITLE
[pkgdb/search]: Create EnvironmentGA class.

### ISSUE THREAD

**Issue by aakropotkin** [flox/pkgdb#123]
Existing Manifest[Raw], Lockfile[Raw], and Environment[Mixin] classes are all written such that users can provide a definition of RegistryRaw.

For an initial General Availability ( GA ) release we intend to limit searches and resolution to a single branch at github:NixOS/nixpkgs/release-23.05 to reduce complexity.

Rather than deleting existing registry handling from existing classes, we will instead create child classes which override the `getRegistrRaw()` routines to return a hard coded registry.

- Lockfiles should still record their locked registry.
- Lockfiles' manifest field should not contain a registry field.

Once created, these classes will be used by existing *Command routines ( handled in another ticket ).
The creation of `Manifest[Raw]GA` and `Lockfile[Raw]GA` is handled in another ticket.

## Acceptance Criteria
- [x] Create `EnvironmentGA` class as described above.

## Progress
- @aakropotkin: https://github.com/flox/pkgdb/pull/145 adds `GAEnvironmentMixin` which is able to support `flox search`.
  + This injects a hard coded registry into _manifest_ files when reading from the filesystem.
  + This approach won't _quite_ work for `pkgdb manifest *` commands because of the lockfile requirements, so there's still work to do here.

**Comment by zmitchell** [comment]
It looks like part of this ticket was implemented here: https://github.com/flox/pkgdb/pull/145

**Comment by aakropotkin** [comment]
> It looks like part of this ticket was implemented here: https://github.com/flox/pkgdb/pull/145

Yes. I can fixup the tickets tomorrow.
