### ISSUE TITLE
[pkgdb/ci]: bug: GitHub Actions OSX isn't fetching from flox caches

### ISSUE THREAD

**Issue by aakropotkin** [flox/pkgdb#139]
I suspect there's an issue restarting the OSX daemon in out GitHub action.

We are able to fetch from official nixpkgs caches, and we're able to push; but we are not fetching cached builds from the `flox` cache.

**Comment by tomberek** [comment]
Likely problem: https://github.com/flox/pkgdb/blob/main/.github/workflows/test.yml#L43

trusted-substituter setting does not specify that it will be used,  just that it is allowed.

Then the store you are pushing to has thr same problem:  https://github.com/flox/pkgdb/blob/main/.github/workflows/test.yml#L59

**Comment by tomberek** [comment]
Next issue may be the daemon restart. Rok mentioned it may need a double kick.

**Comment by tomberek** [comment]
Next issue: the aws setup only applies to systemd: (https://github.com/flox/pkgdb/blob/main/.github/workflows/test.yml#L70)
