### ISSUE TITLE
[pkgdb/locking] unable to update priority of already locked packages

### ISSUE THREAD

**Issue by ysndr** [flox/pkgdb#173]
possibly related to #126

If the priority field of a package is updated in the manifest (e.g. through `flox edit`) the corresponding field in the lockfile remains unchanged:

```bash 
flox install vim
flox install vim-full

cat .flox/env/manifest.lock| jq '.packages["aarch64-darwin"]["vim-full"].priority' 
5


flox edit
# - vim-full = { }
# + vim-full = { priority = 10 }

cat .flox/env/manifest.lock| jq '.packages["aarch64-darwin"]["vim-full"].priority' 
5 ⚡️ should be 10
```

The result is that setting priorities as a measure to resolve conflicts (once we start using the `buildProfile` based `env-builder`) will not work if there is already a lockfile present.

# Accepted when:

* locking a with an existing lockfile should update the priority field if it changed in the original
* changes should apply to all systems (?)

**Comment by ysndr** [comment]
In a somewhat related matter, `flox install` likely needs to accept a priority flag as well to allow installation of conflicting packages without requiring prior manual changes to the manifest. @ghudgins @jennymahmoudi

**Comment by ghudgins** [comment]
what are you setting priority of, the registry? i'm not sure imperative commands are the answer to solving this

**Comment by ysndr** [comment]
Priority of **packages**, if two packages provide the same file, instead of implicitly and unclontrollably shadowing it, we dow produce conflict errors.
To solve these conflicts we accept a `install.<package>.priority` field that allows to control which package to prioritize for the conflicting files.

What I'm asking about is a flag `flox install <package> --priority 1` to mark the package's priority at installation time (or change it if the package is already installed).
Without this if there is a conflict with an existing package you would need to `flox edit` your manifest first to avoid the conflict at install time.
