### ISSUE TITLE
`darwin` package set from `nixpkgs` not scraped by pkgdb

### ISSUE THREAD

**Issue by garbas** [flox/pkgdb#182]
The real issue is in nixpkgs, but it would be nice to have it fixed before we land fix in the upstream

**Comment by aakropotkin** [comment]
Solution : 
add an explicit "allways recurse list" to PkgDb::scrape() which forces recursion into some attributes even if they lack `recurseForDerivations = true`".

This allows us to resolve similar issues in other attributes later.
