### ISSUE TITLE
Bugs when locking a manifest without packages

### ISSUE THREAD

**Issue by ysndr** [flox/pkgdb#189]
locking a manifest that does not include packages ( e.g. only defines a hook ) [1], or an empty `install` table [2] `pkgdb`

* **segfaults** with `--ga-registry`, or
* **hangs** with `--ga-registry` (ignores <kbd>ctrl</kbd> <kbd>C</kbd>
* succeeds immediately without

<details>
<summary>lockfile [1]</summary>

```toml
# manifest.toml

[hook]
script = "test"
```

</details>

<details>
<summary>lockfile [1]</summary>

```toml
# manifest.toml
[install]
```

</details>

**Comment by ysndr** [comment]
So..

* `pkgdb manifest lock --ga-registry manifest.toml` actually works
* `pkgdb manifest lock manifest.toml --ga-registry` does not

I did verify it makes it through the arg parser at least but this behaviour is kinda strange

**Comment by aakropotkin** [comment]
Well that's definitely interesting.

Lets add these as test cases and get them fixed up.

If you'd like I can show you how to hop into `gdb` to track down where the seg-fault occurs as well.
