### ISSUE TITLE
[pkgdb/search]: Catch exceptions and report them over STDOUT as JSON.

### ISSUE THREAD

**Issue by aakropotkin** [flox/pkgdb#64]
While some existing snippets provide a crude implementation of this behavior ( see `main.cc` and `search/command.cc` ), we need a more generic routine for this which can be used across a wider set of commands.

Errors

When an error is caught and is an error we have a code for we will also emit JSON to `STDOUT` instead of search results.

These errors have the following schema:
```
{
  "exit_code": <UNSIGNED INTEGER>,
  "message": <STRING>|<NULL>
}
```

If an unrecognized exception is caught and it does not have a code, a generic code will be used, and message may or may not be set.

Even when we attempt to catch and report errors, it is still possible for `pkgdb` to exit with a non-zero code, and `STDOUT` likely will not provide valid JSON in these cases. We expect this to be a rare occurrence, and will prioritize fixes to such issues as they are discovered; but this behavior is important for any Rust wrappers to handle.

## Acceptance Criteria
- [ ] Capture exceptions for `flox search` subcommand and report them to a JSON structure over `STDOUT`.
- [ ] Strip ANSI escape codes from messages.

**Comment by mkenigs** [comment]
Closing in favor of https://github.com/flox/product/issues/526
