### ISSUE TITLE
test: bats test for other fields

### ISSUE THREAD

**Issue by aakropotkin** [flox/pkgdb#9]
Extend existing `bats` tests to sanity check other fields similar to how `description` and `semver` are audited now.

Basic smoke test each, test for cases where no info is available, test for wrong try ( e.g. `meta.license = 3` ), etc.

If tests do not pass initially add `skip FIXME;` in the test case and proceed to PR.
These can be fixed in other tickets.

**Comment by ghudgins** [comment]
related issue is closed. is this still valid? moving to CLI backlog @aakropotkin

**Comment by aakropotkin** [comment]
Yeah it's done
